# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
 config.vm.box = "dummy"
 config.vm.provider :aws do |aws, override|
   #I would like to use environment variables, rather than hard code them here
   #but cannot get it to work in Windows. If you find out let me know
   aws.access_key_id = "ABCDEFGHTRDWDWDWX"
   aws.secret_access_key = "avEAvdfVADF12341234132412341234"
   #This is the key name as displayed in AWS. You set this at creation time
   aws.keypair_name = "Vagrant"
   aws.ami = "ami-4836a428"
   aws.region = "us-west-2"
   aws.instance_type = "t2.micro"
   
   config.vm.synced_folder '.', '/vagrant', disabled: true
   
#   override.vm.box = "dummy"
   override.ssh.username = "ubuntu"
   #This is the full absolute path plus the filename that contains the key. Don't use relative paths. 
   override.ssh.private_key_path = "C:\\Users\\winusername\\Documents\\aws\\Vagrant.pem"
 end
end

